#:schema node_modules/wrangler/config-schema.json
name = "bankstatementretriever-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
logpush = false

# Custom domain configuration
routes = [
  { pattern = "api.bankstatementretriever.com/*", zone_name = "bankstatementretriever.com" }
]

# Alternative workers.dev route for testing DNS issues
# Access via: https://bankstatementretriever-api.your-subdomain.workers.dev

# Environment Variables
[vars]
ENVIRONMENT = "production"
NODE_ENV = "production"
LOG_LEVEL = "info"
TIMEZONE = "America/New_York"
SUPABASE_URL = "https://yoodxepoxrxzfstfgwst.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_abZYOMdakag57j3NHxhBLw_zemS22cs"
DOMAIN = "bankstatementretriever.com"
PLAID_ENV = "sandbox"

# Cron Triggers - Disabled for MVP
# triggers = [
#   { cron = "0 7 * * *" } # 2 AM ET = 7 AM UTC (standard time)
# ]

# MVP Configuration - KV, Queues, and Durable Objects disabled


# Secrets (set via wrangler secret put)
# SUPABASE_SERVICE_ROLE_KEY
# PLAID_CLIENT_ID
# PLAID_SECRET  
# PLAID_WEBHOOK_SECRET
# ENCRYPTION_KEY
# GOOGLE_DRIVE_CLIENT_ID
# GOOGLE_DRIVE_CLIENT_SECRET
# DROPBOX_CLIENT_ID
# DROPBOX_CLIENT_SECRET
# ONEDRIVE_CLIENT_ID
# ONEDRIVE_CLIENT_SECRET
# SENDGRID_API_KEY
# STRIPE_SECRET_KEY
# WEBHOOK_SIGNING_SECRET


# Analytics and monitoring
[observability]
enabled = true

# MVP: Single environment only - staging and development removed for simplicity