#:schema node_modules/wrangler/config-schema.json
name = "bankstatementretriever-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
logpush = false

# Custom domain configuration
routes = [
  { pattern = "api.bankstatementretriever.com/*", zone_name = "bankstatementretriever.com" }
]

# Environment Variables
[vars]
ENVIRONMENT = "production"
NODE_ENV = "production"
LOG_LEVEL = "info"
TIMEZONE = "America/New_York"
SUPABASE_URL = "https://yoodxepoxrxzfstfgwst.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_abZYOMdakag57j3NHxhBLw_zemS22cs"
DOMAIN = "bankstatementretriever.com"
PLAID_ENV = "sandbox"

# Cron Triggers - Disabled for MVP
# triggers = [
#   { cron = "0 7 * * *" } # 2 AM ET = 7 AM UTC (standard time)
# ]

# KV Namespaces
kv_namespaces = [
  { binding = "BSR_CONFIG", id = "bsr_config_prod", preview_id = "bsr_config_preview" },
  { binding = "BSR_CACHE", id = "bsr_cache_prod", preview_id = "bsr_cache_preview" },
  { binding = "BSR_RATE_LIMITS", id = "bsr_limits_prod", preview_id = "bsr_limits_preview" }
]

# Queues for async processing - Disabled for MVP
# [[queues.producers]]
# binding = "BSR_QUEUE"
# queue = "bsr-main-prod"
# 
# [[queues.consumers]]
# queue = "bsr-main-prod"
# max_batch_size = 10
# max_batch_timeout = 30
# max_retries = 3
# dead_letter_queue = "bsr-main-dlq"

# Durable Objects for coordination - Disabled for MVP
# [[durable_objects.bindings]]
# name = "ACCOUNT_COORDINATOR"
# class_name = "AccountCoordinator"
# 
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"


# Secrets (set via wrangler secret put)
# SUPABASE_SERVICE_ROLE_KEY
# PLAID_CLIENT_ID
# PLAID_SECRET  
# PLAID_WEBHOOK_SECRET
# ENCRYPTION_KEY
# GOOGLE_DRIVE_CLIENT_ID
# GOOGLE_DRIVE_CLIENT_SECRET
# DROPBOX_CLIENT_ID
# DROPBOX_CLIENT_SECRET
# ONEDRIVE_CLIENT_ID
# ONEDRIVE_CLIENT_SECRET
# SENDGRID_API_KEY
# STRIPE_SECRET_KEY
# WEBHOOK_SIGNING_SECRET


# Analytics and monitoring
[observability]
enabled = true

###################
# STAGING ENVIRONMENT
###################
[env.staging]
name = "bankstatementretriever-api-staging"
routes = [
  { pattern = "api-staging.bankstatementretriever.com/*", zone_name = "bankstatementretriever.com" }
]

[env.staging.vars]
ENVIRONMENT = "staging"
NODE_ENV = "development"
LOG_LEVEL = "debug"

# Staging KV Namespaces
[[env.staging.kv_namespaces]]
binding = "BSR_CONFIG"
id = "bsr_config_staging"

[[env.staging.kv_namespaces]]
binding = "BSR_CACHE"
id = "bsr_cache_staging"

[[env.staging.kv_namespaces]]
binding = "BSR_RATE_LIMITS"
id = "bsr_limits_staging"

# Staging Queues - Disabled for MVP
# [[env.staging.queues.producers]]
# binding = "BSR_QUEUE"
# queue = "bsr-main-staging"
# 
# [[env.staging.queues.consumers]]
# queue = "bsr-main-staging"
# max_batch_size = 5
# max_batch_timeout = 10
# max_retries = 2

# Staging Durable Objects - Disabled for MVP
# [[env.staging.durable_objects.bindings]]
# name = "ACCOUNT_COORDINATOR"
# class_name = "AccountCoordinator"
# 
# [[env.staging.durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

###################
# DEVELOPMENT ENVIRONMENT
###################
[env.development]
name = "bankstatementretriever-api-dev"

[env.development.vars]
ENVIRONMENT = "development"
NODE_ENV = "development"
LOG_LEVEL = "debug"
SUPABASE_URL = "https://yoodxepoxrxzfstfgwst.supabase.co"
SUPABASE_ANON_KEY = "sb_publishable_abZYOMdakag57j3NHxhBLw_zemS22cs"

# Development uses local KV storage
[[env.development.kv_namespaces]]
binding = "BSR_CONFIG"
id = "bsr_config_dev"

[[env.development.kv_namespaces]]
binding = "BSR_CACHE"
id = "bsr_cache_dev"

[[env.development.kv_namespaces]]
binding = "BSR_RATE_LIMITS"
id = "bsr_limits_dev"